### PR TITLE
ErrorT -> ExceptT, added liftCRand/liftCRandT

### PR DESCRIPTION
**Pull request by crockeea**
Resolves issue #7.

### CODE REVIEW

**Comment by TomMD** [comment]
Looks good. Can you `git rebase -i HEAD~2` so the temp files don't end up in the tree?

**Comment by crockeea** [comment]
I only know enough git to get me in trouble (as evidenced by my "add -A"). When I do the rebase, I get a file with 

pick 4fbc925 ErrorT -> ExceptT, added liftCRand/liftCRandT
pick 8e0a2a7 removed temp files

Not sure what to do there. Should I remove one line? Do I need to push after saving?

**Comment by TomMD** [comment]
Merged, thank you!

**Comment by TomMD** [comment]
And don't worry about fighting with git - everyone must fight their tool chain some time.  Just don't let it win.

**Pull request closed without merging**
